### ISSUE TITLE
Requirement `^0.2.1` conflicts with other requirements on dependency `apb`

### ISSUE THREAD

**Issue by RHamalainen** [Edu4Chip/Didactic-SoC#10]
After cloning the repository and running `make repository_init`, the following output emerges:

```
bender update
Requirement `^0.2.1` conflicts with other requirements on dependency `apb`.

- package `didactic` requires `e486aa2b7302e3113414c9e5eeeb10d7e36172eb`
- package `apb_uart` requires `^0.2.1`

To resolve this conflict manually, select a revision for `apb` among:
0) `e486aa2b7302e3113414c9e5eeeb10d7e36172eb`
1) `^0.2.1`
Enter a number or hit enter to abort:
```

After this choice, this output emerges:

```
Requirement `^0.38.0` conflicts with other requirements on dependency `axi`.

- package `didactic` requires `69b2dc5b28379855415f4b007b624648a02431bc`
- package `register_interface` requires `^0.38.0`

To resolve this conflict manually, select a revision for `axi` among:
0) `69b2dc5b28379855415f4b007b624648a02431bc`
1) `^0.38.0`
Enter a number or hit enter to abort:
```

After trying all combinations of these options, following error emerges every time:

```
Checkout apb (https://github.com/pulp-platform/apb.git)
    Checkout axi (https://github.com/pulp-platform/axi.git)
bender vendor init
     Cloning ibex (https://github.com/lowRISC/ibex)
     Copying ibex files from upstream
     Cloning pulp (https://github.com/pulp-platform/pulp.git)
     Copying pulp files from upstream

thread 'main' panicked at /home/roni/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bender-0.28.2/src/cmd/vendor.rs:761:67:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:25: repository_init] Error 101
```

Branch: main, commit: adc05ff3acad6ce8f8744146f12f48c5a4533149

**Comment by RHamalainen** [comment]
Error message is caused because bender cannot handle symbolic links which do not point to valid files.

For example following script works:

```
package:
  name: test

vendor_package:
  - name: pulp
    target_dir: vendor_ips/pulp
    upstream: { git: "https://github.com/pulp-platform/pulp.git", rev: "b6ae54700b76395b049742ebfc52c5aaf6e148a5" }
    include_from_upstream:
      - "rtl/tb/README.md"
```

but following does not:

```
package:
  name: test

vendor_package:
  - name: pulp
    target_dir: vendor_ips/pulp
    upstream: { git: "https://github.com/pulp-platform/pulp.git", rev: "b6ae54700b76395b049742ebfc52c5aaf6e148a5" }
    include_from_upstream:
      - "rtl/tb/dpi_models"
```
